# Generated by Django 3.2.6 on 2021-09-05 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_address_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user_profile',
            new_name='user',
        ),
    ]
