# Generated by Django 3.2.6 on 2021-09-11 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fit_tips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fittip',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
