# Generated by Django 3.2.6 on 2021-09-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit_tips', '0004_alter_fittip_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fittip',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
